# Generated by Django 3.0.1 on 2019-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('Phone_number', models.PositiveIntegerField()),
                ('DOB', models.DateField()),
            ],
        ),
    ]
