# Generated by Django 3.0.1 on 2019-12-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DOB',
            new_name='Date_of_Birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email_id',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Phone_number',
            new_name='Phone_Number',
        ),
    ]
