# Generated by Django 3.0.1 on 2019-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0002_auto_20191223_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Date_of_Birth',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
